### ISSUE TITLE
Swiping too quickly after previous swipe causes UI to freeze

### ISSUE THREAD

**Issue by deweydbb** [marcosgriselli/SwipeableTabBarController#73]
I know this is a similar issue to #62 but the solution given was too ambiguous for me to figure out. I don't know if this is a bug or if I have implemented the library incorrectly.

version: 2.1.1
Occurs on physical device and simulators, ios 12, 12.4, 13
Demo project: [https://github.com/deweydbb/TabBarTest](url)

**Comment by marcosgriselli** [comment]
Hi @deweydbb I’m currently on vacation and will check this a week from now 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tkohout** [comment]
+1 Still experiencing this one

**Comment by marcosgriselli** [comment]
Ok, I'll be able to take another look at this in the upcoming weeks. I'm not 100% sure of the cause of the issue but I believe it has something to do with trying to finish the transition before the view is fully loaded.

**Comment by marcosgriselli** [comment]
@deweydbb is the shared repo still valid? I can't seem to reproduce the issue on the simulator (iPhone 11 Pro iOS 13.2.2)

**Comment by tkohout** [comment]
@marcosgriselli I think it would be easier to reproduce on device. Also I noticed this happened more with controllers that might take some time to load and possibly block a main thread for a bit.

**Comment by marcosgriselli** [comment]
Yes, that's my thought as well. I'm trying to generate a case that will reproduce the issue almost consistently so I can test solutions. I'll keep you posted on what I come up with. Of course, if you have a case where the bug is easy to reproduce please share it with me.

**Comment by mrcendre** [comment]
I experienced a similar issue after trying to distribute tasks properly among the my UIViewController's life cycle : in order to smoothly present each view controller, the amount of work in `viewDidLoad` had to be drastically decreased. Data tasks and UI components are loaded and faded in once from `viewDidAppear()` to prevent interferences with the tab bar's transitions when the view controller is displayed for the first time. 

I realised that I had forgotten to chain my child view controllers `viewDidLoad()`, `viewDidAppear()`, `viewWillAppear()` and `viewWillDisappear()` to their `super` methods (when overridden by the said view controllers).

i.e.
```
class FirstViewController : UIViewController {

    override func viewDidAppear(_ animated : Bool) {
        super.viewDidAppear(animated) //This line fixed my problem

        ...

    }
}
```


Although this fixed my problem, after checking the repo @deweydbb provided, it doesn't seem to be the issue in his case. I just wanted to point this as a possible mistake that can cause unpredictable inconsistencies between view controllers while swiping, or even break the view hierarchy (for example, first view controller displayed when the third tab is selected). It may be worth checking that these calls are actually implemented in your project if you're having the same problem.

**Comment by marcosgriselli** [comment]
Thanks for the detailed description @mrcendre do you happen to have some of the code that triggered the problem on `viewDidLoad()`? I want to find a real case where the issue is consistent.

**Comment by johyunmin** [comment]
I did everything I suggested in the above article, but it freezes too. Is there another solution?

**Comment by marcosgriselli** [comment]
@johyunmin do you have an example of your `viewDidLoad()` code that you can share?

**Comment by johyunmin** [comment]
@marcosgriselli 

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    if HomeMain2Manager.shared.pilotAppMain.results == nil{
        appMainPilotList()
    }
    tableView.addSubview(refreshControl)
}
```


This is my viewDidLoad code. I changed it very simply.
appMainPilotList() This code takes the Alamofire api and reloads the tableview.
I have 4 tabs in total and the 1 , 3 tabs are WKWebviews.
But still happens.

**Comment by marcosgriselli** [comment]
We'll use issue #52 for this problem.
