### ISSUE TITLE
Detect a swipe vs tap

### ISSUE THREAD

**Issue by MaxHasADHD** [marcosgriselli/SwipeableTabBarController#97]
Is it possible to detect when the page changes from a swipe instead of a tap?

**Comment by marcosgriselli** [comment]
@MaxHasADHD `SwipeableTabBarController` is a subclass of `UITabBarController` so it comes with the same mechanisms. You can use KVO to observe the `selectedViewController` or `selectedIndex` properties that will change when swiping ends. Or if you're using Combine you can do it with publishers: 

```swift 
publisher(for: \.selectedIndex).sink { newIndex in
    print("New index: \(newIndex)")
}.store(in: &cancellables)
publisher(for: \.selectedViewController).sink { newValue in
    print("New view controller: \(newValue)")
}.store(in: &cancellables)
```

I'm closing this since its not a library-specific issue but a `UITabBarController` question.
